CREATE TABLE `blogPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(255) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`author` varchar(255),
	`authorRole` varchar(255),
	`category` varchar(100),
	`tags` text,
	`featuredImage` text,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`metaKeywords` text,
	`isPublished` int unsigned NOT NULL DEFAULT 0,
	`publishedAt` timestamp,
	`readTime` int,
	`viewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blogPosts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blogPosts_slug_unique` UNIQUE(`slug`)
);
